'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),net=require('node:net');
const {execFileSync}=require('node:child_process'),{randomUUID,randomBytes}=require('node:crypto');
const {fixture,TOKEN,APP}=require('./meta-marketing-oauth-fixture.cjs'),C=require('../src/meta-marketing-oauth-contract'),E=require('../src/meta-marketing-enrollment-contract'),M=require('../src/meta-marketing-contract');
const {allowPort,removePort}=require('./offline-guard.cjs'),runtime=require('../src/meta-marketing-oauth-main'),{drainAudit}=require('../src/audit');
const {createIntegrationsBrokerClient}=require('../../../src/lib/integrationsBrokerClient');
const {createMetaMarketingBrokerReader}=require('../../../src/services/metaMarketingBrokerReader.service');
test('actual TLS runtime activates the selected candidate, serves the CRM read contract, survives restart and independently revokes',async t=>{
  const f=fixture(t,{enrollment:true}),config=f.config;
  execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',config.tlsKeyFile,'-out',config.tlsCertFile,'-days','1','-subj','/CN=127.0.0.1','-addext','subjectAltName=IP:127.0.0.1'],{stdio:'ignore'});
  fs.chmodSync(config.tlsKeyFile,0o600);fs.chmodSync(config.tlsCertFile,0o600);
  const probe=net.createServer();await new Promise(resolve=>probe.listen(0,'127.0.0.1',resolve));config.port=probe.address().port;await new Promise(resolve=>probe.close(resolve));allowPort(config.port);
  const filename=path.join(f.dir,'enrollment-config.json');fs.writeFileSync(filename,JSON.stringify(config),{mode:0o600});const events=[];
  const sink={async write(row){events.push(JSON.parse(row.event));return {versionId:'fictitious-enrollment-s3',digest:row.digest};}};
  const awsFactory=async()=>({secrets:f.aws,sink,close(){}});let app=await runtime.main(filename,{awsFactory,http:f.http});
  t.after(async()=>{if(app)await app.close();removePort(config.port);});
  const clients={};for(const [name,key,keyId]of [['gateway',f.gateway,'qa-gateway'],['control',f.control,'qa-control'],['reader',f.reader,'qa-reader'],['assetControl',f.assetControl,'qa-asset-control']])
    clients[name]=createIntegrationsBrokerClient({origin:`https://127.0.0.1:${config.port}`,audience:config.policy.audience,keyId,privateKey:key.privateKey.export({type:'pkcs8',format:'pem'}),ca:fs.readFileSync(config.tlsCertFile)});
  const flowId=randomUUID(),state=randomBytes(32).toString('base64url'),scopeDigest=C.hash('FICTITIOUS_WHOLE_SCOPE'),enrollmentId=randomUUID();
  await clients.gateway.execute(f.command(C.OPERATIONS.begin,{state,expiresAt:Date.now()+590000,scopeDigest,clinicSetDigest:C.clinicDigest(f.binding.metaMarketingOAuth)},{requestId:flowId}));
  const candidate=(await clients.gateway.execute(f.command(C.OPERATIONS.finish,{flowId,state,code:'FICTITIOUS_TLS_ENROLLMENT_CODE'}))).data.candidate;
  const payload={enrollmentId,flowId,scopeDigest,candidateDigest:candidate.digest,assetRefs:['meta-ad_account:301','meta-facebook_page:401','meta-instagram_business:501']};
  const p=(await clients.gateway.execute(f.command(E.OPERATIONS.prepare,payload))).data;
  const expected={tenantRef:'clinic:71',connectionRef:f.binding.connectionRef,assetRef:'meta-ad_account:301',kind:'ad_account',id:'301',parentPageId:null,appId:'101',subjectId:'201'};
  const reader=createMetaMarketingBrokerReader({client:clients.reader,assertContext:async()=>structuredClone(expected)});
  await assert.rejects(reader.read({},M.ASSET,{authorize:async()=>{}}),{code:'scope_denied'});
  const activation=f.command(E.OPERATIONS.activate,{enrollmentId,scopeDigest,selectionDigest:p.selectionDigest});
  const active=await clients.gateway.execute(activation);assert.equal(active.data.accessBlocked,false);
  await app.close();app=null;app=await runtime.main(filename,{awsFactory,http:f.http});
  assert.equal((await clients.gateway.execute(activation)).replayed,true);
  let authorityChecks=0;const asset=await reader.read({},M.ASSET,{authorize:async()=>{authorityChecks++;}});assert.equal(asset.id,'act_301');assert.equal(authorityChecks,2);
  assert.equal((await reader.read({},M.STATUS,{authorize:async()=>{}})).credentialValid,true);
  const before=f.state.awsCalls.length;
  await assert.rejects(clients.gateway.execute(f.command(M.ASSET,{}, {assetRef:expected.assetRef})),{code:'scope_denied'});
  const revoked=await clients.assetControl.execute(f.command(M.REVOKE,{}, {assetRef:expected.assetRef}));assert.equal(revoked.data.revoked,true);
  await assert.rejects(reader.read({},M.ASSET,{authorize:async()=>{}}),{code:'asset_revoked'});
  assert.equal(f.state.awsCalls.length,before);
  assert.equal((await clients.control.execute(f.command(E.OPERATIONS.revoke,{enrollmentId}))).data.status,'revoked');
  assert.equal(f.state.codes,1);assert.equal(f.state.puts,1);
  await drainAudit(app.store,sink);assert.equal(app.store.backlog().pending,0);assert(events.some(v=>v.reason==='meta_enrollment_activate_completed'));
  for(const secret of [TOKEN,APP,state,'FICTITIOUS_TLS_ENROLLMENT_CODE'])assert(!JSON.stringify(events).includes(secret));
  const heads=app.store.db.prepare('SELECT state,assets FROM meta_marketing_enrollments').all();assert.equal(heads.length,1);assert.equal(heads[0].state,'revoked');
  await app.close();app=null;
});
