'use strict';
// Synthetic source families only; no exports, database, real identities or app.
const test=require('node:test'),assert=require('node:assert/strict');
const {hash,normalizeContacts}=require('../../lib/cliniccloud-import/adapter');
const auditCore=require('../../lib/cliniccloud-import/new-patients-audit');
const apply=require('../../lib/cliniccloud-import/new-patients-apply');
const resolutions=require('../../lib/cliniccloud-import/reviewed-contact-resolutions');
const {planContacts}=require('../../lib/cliniccloud-import/planner');
const patches=require('../../lib/cliniccloud-import/contacts-apply');
const {canonicalImportedBirthDateHold,canonicalImportedBaseline}=require('../cliniccloud-import-snapshot');
const clone=value=>JSON.parse(JSON.stringify(value));

function fixture(){
 const now=Date.now(),at=new Date(now).toISOString(),ids=['8000001','8000002','8000003'];
 const contacts=ids.map((id,i)=>({source_row:2+i,values:{IDCONTACTO:id,NUM:String(90001+i),NOMBRE:`Persona${i}`,APELLIDOS:`Prueba${hash(String(i)).slice(0,12)}`,'TELF. MOVIL':String(600100001+i),EMAIL:`person${i}@example.invalid`,DNI:'','F. NACIMIENTO':i===1?'03/09/2026':'02/01/1980',ALTA:i===1?'01-09-2026 10:00:00':'07-07-2026 10:00:00',ESTADO:'ACTIVO'}}));
 const appointment=(i,id,service,state,day,conceptContact=ids[i])=>({idCita:id,idContacto:ids[i],idAgenda:500,agenda:{idAgenda:500,idEmpresa:5880,nombre:'CAPILARES'},fechaIni:day,fechaFin:day,horaIni:'10:00:00',horaFin:'10:30:00',estado:state,pagado:0,marcaRealizada:state===1?`${day} 10:30:00`:null,conceptos:[{idCitaConcepto:id+1000,idCita:id,idContacto:conceptContact,idServicio:service,pagado:0}]});
 const zero=appointment(0,101,501,0,'2026-07-08',0),paid=appointment(0,102,501,3,'2026-07-10'),dob=appointment(1,201,501,3,'2026-09-03'),admin=appointment(2,301,502,1,'2026-07-08');
 const patients=[{contact_id:ids[0],rows:[zero,paid]},{contact_id:ids[1],rows:[dob]},{contact_id:ids[2],rows:[admin]}];
 const sources=Object.fromEntries(['contacts','appointments','historic_contacts','historic_types','historic_services','live_histories','live_state_labels'].map(role=>[role,{file:{role,name:`synthetic-${role}.json`,sha256:hash(`synthetic-${role}`)},rows:[]} ]));
 sources.contacts.rows=contacts;
 sources.historic_types.rows=[{values:{idTipoServicio:'260902',nombre:'CAPILAR'}}];
 sources.historic_services.rows=[{values:{idServicio:501,idTipoServicio:'260902',nombre:'Servicio capilar ficticio'}},{values:{idServicio:502,idTipoServicio:'260902',nombre:'PRP SESION FACIAL Y CAPILAR'}}];
 sources.live_histories.data={version:1,captured_at:at,origin:'https://app.clinic-cloud.com',source_endpoint:'/apps/contacto/pestanas-contacto-ficha/php/citas/citas.api.php/get-citas',policy:'read_only_no_clinical_or_economic_mutations',patients};
 sources.live_state_labels.data={captured_at:at,source:'patient_appointments_table_display_renderer',observations:[[0,'Pendiente'],[1,'Realizada'],[3,'Pagada'],[-1,'No Acude'],[-2,'Anulada']].map(([code,label])=>({code,label}))};
 const base=(i,kind,expected)=>({kind,source_contact_id:ids[i],source_contact_row_sha256:hash(contacts[i].values),history_number:contacts[i].values.NUM,history_sha256:hash(patients[i]),reviewer_user_id:1,reviewed_by:'Synthetic operator',reason:'Exact synthetic source proof reviewed.',expected});
 const decisions=[base(0,'zero_concept_contact_parent_scope',{source_appointment_id:'101',parent_sha256:hash(zero),company_id:5880,concept_contact_id:'0',parent_contact_id:ids[0],source_concept_id:'1101',concept_sha256:hash(zero.conceptos[0])}),base(1,'invalid_birth_date_omission',{raw_birth_date:'03/09/2026',normalized_birth_date:'2026-09-03',source_creation_local:'2026-09-01T10:00:00',canonical_birth_date:null,age_status:'unknown',later_demographic_review_required:true}),base(2,'primary_clinic_from_observed_agenda',{source_appointment_id:'301',parent_sha256:hash(admin),company_id:5880,clinic_id:66,source_state:1,agenda_id:500,agenda_name:'CAPILARES',performed_local:'2026-07-08T10:30:00',ambiguous_service_id:'502',agenda_mapping:{kind:'reviewed_administrative_agenda_mapping',clinic_id:66,company_id:5880,agenda_id:500,agenda_name:'CAPILARES',anchor_mapping_sha256:hash({company_id:5880,agenda_id:500,agenda_name:'CAPILARES',clinic_id:66,anchor_sha256:hash(admin),administrative_only:true})}})];
 let receipt;
 function seal(){const body={version:resolutions.VERSION,source_account:'cliniccloud-5880',reviewed_at:at,expires_at:new Date(now+3600000).toISOString(),decisions,source_files:Object.values(sources).filter(s=>s.file.role!==resolutions.ROLE).map(s=>({role:s.file.role,name:s.file.name,sha256:s.file.sha256}))};receipt={...body,resolutions_sha256:hash(body)};sources[resolutions.ROLE]={file:{role:resolutions.ROLE,name:'synthetic-reviewed.json',sha256:hash(receipt)},data:receipt};return receipt;}
 seal();
 const live={group_id:29,clinic_ids:[66,72],patients:[],source_links:[]};
 const build=()=>auditCore.buildNewPatientsAudit({sources,live,coverage:{start:'2026-08-01',end:'2026-12-31'},contactsAsOf:'2026-10-04'});
 const prepare=()=>{const audit=build(),review={source_audit_sha256:audit.plan_sha256,prepared_by:'Synthetic operator',decisions:audit.rows.map(r=>({source_contact_id:r.source_contact_id,disposition:'retain',reason:'Synthetic source and identity checks.'}))};return apply.prepareNewPatients({audit,sources,review,live});};
 return {sources,ids,contacts,patients,zero,dob,admin,decisions,live,build,prepare,seal,get receipt(){return receipt;}};
}

function storedSnapshot(operation){return {version:'cliniccloud_contact_snapshot/1',source_account:'cliniccloud-5880',contact:{idContacto:operation.source_contact_id,num:operation.history_number},fields:operation.source_fields,stored_fields:{...operation.source_fields,birth_date:''},provenance:operation.provenance,import:{automation_policy:'hold',messages_enabled:false,operator_resolution:operation.operator_resolution,birth_date_hold:{version:1,active:true,decision_sha256:operation.operator_resolution.decision_sha256,age_status:'unknown',later_demographic_review_required:true}}};}

test('bounded v4 resolves exactly three administrative identities without changing source',()=>{const f=fixture(),before=hash(f.sources),audit=f.build(),pkg=f.prepare();assert.equal(audit.manifest.version,'cliniccloud-new-patients-audit/4');assert.equal(audit.rows.length,3);assert.equal(pkg.operations.length,3);assert.equal(hash(f.sources),before);assert.equal(pkg.appointments_created,false);assert.equal(pkg.messages_enabled,false);const dob=pkg.operations.find(o=>o.source_contact_id===f.ids[1]);assert.equal(dob.payload.fecha_nacimiento,null);assert.equal(dob.source_fields.birth_date,'2026-09-03');const admin=pkg.operations.find(o=>o.source_contact_id===f.ids[2]);assert.equal(admin.payload.clinica_id,66);assert.equal(admin.primary_rule,'operator_reviewed_observed_agenda');assert.equal(admin.primary_evidence[0].administrative_only,true);assert.equal(admin.primary_evidence[0].treatment_id,undefined);apply.verifyPackage(pkg);});
test('without opt-in original zero-concept scope rejection remains',()=>{const f=fixture();delete f.sources[resolutions.ROLE];assert.throws(f.build,/OBSERVED_HISTORY_CONCEPT_SCOPE_INVALID/);});
test('without opt-in invalid DOB and broad service remain deferred',()=>{const f=fixture();delete f.sources[resolutions.ROLE];f.zero.conceptos[0].idContacto=f.ids[0];const audit=f.build();assert(audit.rows.find(r=>r.source_contact_id===f.ids[1]).reasons.includes('BIRTH_DATE_AFTER_SOURCE_CREATION'));assert.equal(audit.rows.find(r=>r.source_contact_id===f.ids[2]).status,'defer');});
test('contact/source/history/canonical expected/reviewer/reason are mandatory exact proof',()=>{for(const mutate of [f=>f.decisions[0].source_contact_id='999999',f=>f.decisions[0].source_contact_row_sha256=hash('wrong'),f=>f.decisions[0].history_sha256=hash('wrong'),f=>f.decisions[0].reviewed_by='',f=>f.decisions[0].reviewer_user_id=0,f=>f.decisions[0].reason='',f=>f.decisions[1].expected.canonical_birth_date='1980-01-01',f=>f.decisions[1].expected.age_status='adult',f=>f.decisions[2].expected.clinic_id=72]){const f=fixture();mutate(f);f.seal();assert.throws(f.build,/REVIEWED_CONTACT/);}});
test('unknown fields, broader scope, changed source files and expired review fail closed',()=>{for(const mutate of [f=>f.decisions[0].force=true,f=>f.decisions[0].expected.other_contact_id=f.ids[1],f=>f.decisions.pop(),f=>f.decisions.push(clone(f.decisions[0])),f=>f.sources.contacts.file.sha256=hash('newfile')]){const f=fixture();mutate(f);if(f.decisions.length!==3||f.decisions[0].force||f.decisions[0].expected.other_contact_id)f.seal();assert.throws(f.build,/REVIEWED_CONTACT/);}const f=fixture();f.receipt.expires_at='2020-01-01T00:00:00Z';const {resolutions_sha256,...body}=f.receipt;f.receipt.resolutions_sha256=hash(body);assert.throws(f.build,/EXPIRED/);});
test('different positive concept contacts and foreign parents never use zero exception',()=>{for(const mutate of [f=>f.zero.conceptos[0].idContacto=f.ids[1],f=>f.zero.idContacto=f.ids[1],f=>f.zero.agenda.idEmpresa=123,f=>f.zero.conceptos[0].idCita=102]){const f=fixture();mutate(f);f.decisions[0].history_sha256=hash(f.patients[0]);f.decisions[0].expected.parent_sha256=hash(f.zero);f.decisions[0].expected.concept_sha256=hash(f.zero.conceptos[0]);f.seal();assert.throws(f.build,/REVIEWED_CONTACT/);}});
test('administrative clinic cannot come from a pending, wrong-agenda or absent performed anchor',()=>{for(const mutate of [f=>f.admin.estado=0,f=>f.admin.agenda.nombre='CELIA',f=>f.admin.marcaRealizada=null,f=>f.admin.agenda.idAgenda=501]){const f=fixture();mutate(f);f.decisions[2].history_sha256=hash(f.patients[2]);f.decisions[2].expected.parent_sha256=hash(f.admin);f.seal();assert.throws(f.build,/REVIEWED_CONTACT/);}});
test('writer recomputes proof and rejects rehashed false audit assignment/receipt',()=>{const f=fixture(),audit=f.build();audit.rows[0].operator_resolution.reason='Rehashed unauthorized change';const {plan_sha256,...body}=audit;audit.plan_sha256=hash(body);assert.throws(()=>apply.operationsFromAudit(audit,f.sources),/AUDITED_RESOLUTION_CHANGED/);});
test('DOB omission keeps raw/stored baselines separate with durable unknown-age hold',()=>{const f=fixture(),op=f.prepare().operations.find(o=>o.source_contact_id===f.ids[1]),s=storedSnapshot(op),row={source_column:'cliniccloud_contact_snapshot',source_contact_id:op.source_contact_id,history_number:op.history_number,canonical_snapshot:JSON.stringify(s)};assert.equal(canonicalImportedBaseline([row]).birth_date,'2026-09-03');assert.equal(canonicalImportedBaseline([row],'stored_fields').birth_date,'');const hold=canonicalImportedBirthDateHold([row]);assert.equal(hold.age_status,'unknown');assert.equal(hold.raw_birth_date,'03/09/2026');const bad=clone(s);bad.import.birth_date_hold.active=false;assert.throws(()=>resolutions.storedBirthDateHold(bad),/STORED_BIRTH_HOLD_INVALID/);});
test('unchanged raw DOB preserves NULL; a changed DOB becomes review, never a patch',()=>{const f=fixture(),op=f.prepare().operations.find(o=>o.source_contact_id===f.ids[1]),s=storedSnapshot(op),hold=resolutions.storedBirthDateHold(s),patient={id:10,source_contact_ids:[op.source_contact_id],fields:{...op.source_fields,birth_date:''},last_imported_fields:op.source_fields,last_imported_local_fields:{...op.source_fields,birth_date:''},birth_date_hold:hold},contact={source_contact_id:op.source_contact_id,fields:clone(op.source_fields),provenance:{row_sha256:hash('latest')}};const unchanged=planContacts([contact],[],[patient]).actions[0];assert.equal(unchanged.action,'link_patient');assert.equal(unchanged.fields_patch.birth_date,undefined);contact.fields.birth_date='1980-01-02';const changed=planContacts([contact],[],[patient]).actions[0];assert.equal(changed.action,'review');assert.equal(changed.fields_patch.birth_date,undefined);assert.equal(changed.demographic_review.current_source_value,'1980-01-02');});
test('writer revalidates active birth hold from full persisted identity rows',()=>{const f=fixture(),op=f.prepare().operations.find(o=>o.source_contact_id===f.ids[1]),s=storedSnapshot(op),row={id_paciente:10,clinica_id:66,nombre:'Persona',apellidos:'Ejemplo',fecha_nacimiento:null},candidate={patient_id:10,expected_clinic_id:66,source_contact_id:op.source_contact_id,expected_fields:patches.fieldsOf(row),fields_patch:{birth_date:'1980-01-02'}},links=[{source:'cliniccloud',source_column:'idContacto',value:op.source_contact_id},{source:'cliniccloud',source_column:'cliniccloud_contact_snapshot',value:JSON.stringify(s)}];assert.throws(()=>patches.validateCurrent(candidate,row,links),/REVIEWED_INVALID_SOURCE_BIRTH_DATE_HELD/);candidate.fields_patch={email:'qa@example.invalid'};patches.validateCurrent(candidate,row,links);});
test('package integrity rejects even a rehashed DOB replacement for a reviewed omission',()=>{const f=fixture(),pkg=f.prepare(),op=pkg.operations.find(o=>o.source_contact_id===f.ids[1]);op.payload.fecha_nacimiento='1980-01-02T00:00:00Z';const {operation_sha256,...body}=op;op.operation_sha256=hash(body);const {package_sha256,...packageBody}=pkg;pkg.package_sha256=hash(packageBody);assert.throws(()=>apply.verifyPackage(pkg),/OMISSION_PAYLOAD_CHANGED/);});
test('administrative mapping digest is bound to its actual exact source anchor',()=>{const f=fixture();f.decisions[2].expected.agenda_mapping.anchor_mapping_sha256='a'.repeat(64);f.seal();assert.throws(f.build,/ADMINISTRATIVE_AGENDA_EXPECTATION_INVALID/);});
test('reviewed creation is CRM-only and never a retained subset',async()=>{const f=fixture(),pkg=f.prepare();pkg.database_target='dev';const {package_sha256,...body}=pkg;pkg.package_sha256=hash(body);assert.throws(()=>apply.verifyPackage(pkg),/PACKAGE_SCOPE_INVALID/);const audit=f.build(),review={source_audit_sha256:audit.plan_sha256,prepared_by:'Synthetic operator',decisions:audit.rows.map((r,i)=>({source_contact_id:r.source_contact_id,disposition:i?'retain':'defer',reason:'Explicit synthetic decision.'}))};assert.throws(()=>apply.prepareNewPatients({audit,sources:f.sources,review,live:f.live}),/COMPLETE_RETAIN_REQUIRED/);await assert.rejects(require('../cliniccloud-import-new-patients-apply').run(['--target','dev','--operator-resolutions','synthetic.json']),/CRM_TARGET_REQUIRED/);});
test('legacy malformed snapshot does not block unrelated email patches',()=>{const row={id_paciente:10,clinica_id:66,nombre:'Persona',apellidos:'Ejemplo',fecha_nacimiento:null},candidate={patient_id:10,expected_clinic_id:66,source_contact_id:'800001',expected_fields:patches.fieldsOf(row),fields_patch:{email:'qa@example.invalid'}},links=[{source:'cliniccloud',source_column:'idContacto',value:'800001'},{source:'cliniccloud',source_column:'cliniccloud_contact_snapshot',value:'not JSON'}];patches.validateCurrent(candidate,row,links);candidate.fields_patch={birth_date:'1980-01-02'};assert.throws(()=>patches.validateCurrent(candidate,row,links),/CANONICAL_CONTACT_SNAPSHOT_INVALID/);});

function transactionFixture(pkg,expireDuring=false){
 const start=Date.parse(pkg.operations[0].operator_resolution.reviewed_at),state={data:{group_id:29,clinic_ids:[66,72],patients:[],source_links:[]},commits:0,inserts:0,transactions:0,clock:start};
 const store={captureGroup:async()=>clone(state.data),transaction:async callback=>{state.transactions++;const working=clone(state.data);await callback({captureGroup:async()=>clone(working),insertPatient:async(op,payload)=>{const id=1000+state.inserts++;working.patients.push({id_paciente:id,...payload});working.source_links.push({paciente_id:id,source_contact_id:op.source_contact_id,history_number:op.history_number});if(expireDuring&&state.inserts===3)state.clock=start+3600001;return {patient_id:id,after_sha256:hash(payload)};}});state.data=working;state.commits++;}};
 const execute=()=>apply.executeNewPatients({pkg,store,journal:{append:async()=>{}},now:()=>state.clock,publicId:()=>`pac_synthetic_${state.inserts}`,approval:{package_sha256:pkg.package_sha256,reviewed_by:'Synthetic operator',acknowledge_native_create_race:true,automation_policy:'hold',backup_manifest_sha256:'b'.repeat(64),expires_at:new Date(start+7200000).toISOString()}});
 return {state,execute,start};
}
test('review expiry is rechecked before first insertion independently of approval expiry',async()=>{const f=fixture(),pkg=f.prepare(),t=transactionFixture(pkg);t.state.clock=t.start+3600001;await assert.rejects(t.execute,/REVIEWED_CONTACT_RESOLUTIONS_EXPIRED/);assert.equal(t.state.transactions,0);assert.equal(t.state.inserts,0);});
test('review expiry immediately before commit rolls the whole canonical batch back',async()=>{const f=fixture(),pkg=f.prepare(),t=transactionFixture(pkg,true);await assert.rejects(t.execute,/REVIEWED_CONTACT_RESOLUTIONS_EXPIRED/);assert.equal(t.state.inserts,3);assert.equal(t.state.commits,0);assert.equal(t.state.data.patients.length,0);});
test('operator review cannot outlive the remaining authenticated source history/labels lease',()=>{const f=fixture();f.sources.live_histories.data.captured_at=new Date(Date.now()-110*60000).toISOString();assert.throws(f.build,/SOURCE_LEASE_INVALID/);});
