'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {preparePartialIdentityReview}=require('../../lib/cliniccloud-import/contact-alias-evidence');
const {validateContactAlias}=require('../../lib/cliniccloud-import/contact-aliases');
const now=Date.parse('2026-09-21T16:00:00Z');
function fixture(){const source={source_contact_id:'456',fields:{name:'Mariana Segunda',surname:'Ficticia Ejemplo',phone:'+34 600 000 001'}};
 const patient={id_paciente:9,clinica_id:72,nombre:'Mariana',apellidos:'Segunda M',telefono_movil:'600000001'};
 const link={source_contact_id:'456',patient_id:9,reviewed_partial_identity:{policy:'phone_and_clear_partial_name',policy_reference:'Owner authorized rule; operator review, not a claimed pair confirmation',reviewed_at:'2026-09-21T15:50:00Z',patient_full_name:'Mariana Segunda M',reason:'Unique telephone and complete compound given name; only an initial follows in reception.'}};
 return {source,contacts:[source],link,reviewedBy:'Operator review under owner policy',now,live:{patients:[patient],source_links:[]}};}
function check(f){const evidence=preparePartialIdentityReview(f);return validateContactAlias(f.source,9,f.live,evidence);}
test('bounded reviewed compound name and unique phone yields only an alias without mutating the patient',()=>{const f=fixture(),before=JSON.stringify(f);assert.throws(()=>validateContactAlias(f.source,9,f.live),/NOT_UNIQUE/);const r=check(f);assert.equal(r.patient.id_paciente,9);assert.equal(r.evidence,'operator_reviewed_unique_phone_name_prefix');assert.equal(JSON.stringify(f),before);});
test('a full given name plus a truncated surname prefix is supported',()=>{const f=fixture();f.source.fields={...f.source.fields,name:'Margarita',surname:'Del Ejemplo Ficticio'};f.live.patients[0].nombre='Margarita';f.live.patients[0].apellidos='Del';f.link.reviewed_partial_identity.patient_full_name='Margarita Del';assert.equal(check(f).patient.id_paciente,9);});
test('shared source/local telephones and a phone with no corroborated name stop',()=>{for(const mutate of [f=>f.contacts.push({...f.source,source_contact_id:'789'}),f=>f.live.patients.push({...f.live.patients[0],id_paciente:10,nombre:'Otra'}),f=>f.source.fields.phone='600000002']){const f=fixture();mutate(f);assert.throws(()=>check(f),/PHONE_NOT_UNIQUE/);}});
test('full conflicting tokens, a lone given name, nicknames, reordered names and initials do not match',()=>{for(const [name,surname] of [['Mariana','Otro'],['Mariana',''],['Mari','Segunda'],['Segunda','Mariana'],['M','Segunda']]){const f=fixture();Object.assign(f.live.patients[0],{nombre:name,apellidos:surname});f.link.reviewed_partial_identity.patient_full_name=`${name} ${surname}`;assert.throws(()=>check(f),/NAME_NOT_CORROBORATED/);}});
test('document, birth date, external ownership and clinic boundaries still apply',()=>{for(const mutate of [f=>{f.source.fields.national_id='123';f.live.patients[0].dni='456';},f=>{f.source.fields.birth_date='1980-01-01';f.live.patients[0].fecha_nacimiento='1981-01-01';},f=>f.live.source_links.push({paciente_id:10,source_contact_id:'456'}),f=>f.live.patients[0].clinica_id=59]){const f=fixture();mutate(f);assert.throws(()=>check(f),/CONFLICT|ALREADY_OWNED|SCOPE_INVALID/);}});
test('review cannot impersonate user pair confirmation or omit operator reason, policy, date, reference',()=>{for(const patch of [{reason:'x'},{policy:'phone_only'},{policy_reference:''},{reviewed_at:'2026-09-20T15:50:00Z'},{reviewed_at:'2026-09-22T15:50:00Z'}]){const f=fixture();Object.assign(f.link.reviewed_partial_identity,patch);assert.throws(()=>check(f),/PARTIAL_REVIEW_REQUIRED/);}const f=fixture();f.link.confirmed_identity=true;assert.throws(()=>check(f),/PARTIAL_REVIEW_REQUIRED/);});
test('changed local name after review is rejected and replay is stable',()=>{const f=fixture(),e=preparePartialIdentityReview(f);f.live.source_links.push({paciente_id:9,source_contact_id:'456'});assert.equal(validateContactAlias(f.source,9,f.live,e).already_linked,true);f.live.patients[0].apellidos='Segunda F';assert.throws(()=>validateContactAlias(f.source,9,f.live,e),/NAME_CHANGED/);});
