'use strict';
module.exports = (sequelize, D) => sequelize.define('GoogleAdsEnrollmentRequest', {
  enrollment_id: { type: D.UUID, primaryKey: true, allowNull: false },
  scope_key: { type: D.STRING(64), allowNull: false },
  google_connection_id: { type: D.INTEGER, allowNull: false },
  google_user_id: { type: D.STRING(128), allowNull: false },
  connection_ref: { type: D.STRING(128), allowNull: false },
  scope_ref: { type: D.STRING(128), allowNull: false },
  tenant_clinic_id: { type: D.INTEGER, allowNull: false },
  customer_id: { type: D.CHAR(10), unique: true, allowNull: false },
  login_customer_id: { type: D.CHAR(10), allowNull: true },
  clinic_ids: { type: D.TEXT, allowNull: false },
  clinic_count: { type: D.INTEGER.UNSIGNED, allowNull: false },
  clinic_digest: { type: D.CHAR(64), allowNull: false },
  scope_digest: { type: D.CHAR(64), allowNull: false },
  mapping_id: { type: D.INTEGER, unique: true, allowNull: true },
  actor_user_id: { type: D.INTEGER, allowNull: false },
  session_ref: { type: D.UUID, allowNull: false },
  session_expires_at: { type: D.DATE(3), allowNull: false },
  prepare_request_id: { type: D.UUID, unique: true, allowNull: false },
  activate_request_id: { type: D.UUID, unique: true, allowNull: false },
  revoke_request_id: { type: D.UUID, unique: true, allowNull: false },
  state: { type: D.ENUM('prepare_pending', 'prepared', 'activate_pending', 'activation_confirmed', 'active', 'revoke_pending', 'revoked'),
    allowNull: false, defaultValue: 'prepare_pending' },
  requested_at: { type: D.DATE(3), allowNull: false }, updated_at: { type: D.DATE(3), allowNull: false },
  attempts: { type: D.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
  next_attempt_at: { type: D.DATE(3), allowNull: false }, lease_token: { type: D.UUID, allowNull: true },
  lease_until: { type: D.DATE(3), allowNull: true }, last_error: { type: D.STRING(64), allowNull: true },
}, { tableName: 'GoogleAdsEnrollmentRequests', timestamps: false });
