'use strict';
module.exports = (sequelize, D) => sequelize.define('GoogleOAuthBrokerRequest', {
  flow_id: { type: D.UUID, primaryKey: true, allowNull: false },
  activation_id: { type: D.UUID, unique: true, allowNull: false },
  state_hash: { type: D.STRING(64), unique: true, allowNull: false },
  binding_digest: { type: D.STRING(64), allowNull: false },
  google_user_id: { type: D.STRING(128), allowNull: false },
  google_connection_id: { type: D.INTEGER, allowNull: false },
  connection_ref: { type: D.STRING(128), allowNull: false },
  asset_ref: { type: D.STRING(128), allowNull: false },
  clinica_id: { type: D.INTEGER, allowNull: false },
  scope_key: { type: D.STRING(64), allowNull: false },
  clinic_ids: { type: D.JSON, allowNull: false },
  actor_user_id: { type: D.INTEGER, allowNull: false },
  session_ref: { type: D.UUID, allowNull: false },
  return_to: { type: D.STRING(256), allowNull: false },
  requested_at: { type: D.DATE(3), allowNull: false },
  expires_at: { type: D.DATE(3), allowNull: false },
  state: { type: D.STRING(24), allowNull: false },
  next_attempt_at: { type: D.DATE(3), allowNull: false },
  attempts: { type: D.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
  lease_token: { type: D.UUID, allowNull: true },
  lease_until: { type: D.DATE(3), allowNull: true },
  last_error: { type: D.STRING(48), allowNull: true },
  completed_at: { type: D.DATE(3), allowNull: true },
}, { tableName: 'GoogleOAuthBrokerRequests', timestamps: false, indexes: [
  { name: 'idx_google_oauth_delivery', fields: ['state', 'next_attempt_at', 'lease_until'] },
  { name: 'idx_google_oauth_connection', fields: ['google_connection_id', 'requested_at'] },
] });
